### ISSUE TITLE
Incompatible with drippyloadingscreen

### ISSUE THREAD

**Issue by Em4rg** [Talsumi/MCStatuesClassic#2]
When opening the client, it keeps loading endlessly

**Comment by Talmori** [comment]
This is.. odd. After a cursory look I see no code in DrippyLoadingScreen that should conflict with this mod. Does the issue still occur without DrippyLoadingScreen, but with Konkrete still installed?

**Comment by Em4rg** [comment]
I removed DrippyLoadingScreen from the list of my mods and the error no longer occurred, I got a new one when I wanted to enter my server, it crashed minecraft.

**Comment by Talmori** [comment]
Can you post the crash log?

**Comment by Talmori** [comment]
Also is this happening in 1.18 or 1.19?

**Comment by Em4rg** [comment]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2022-10-31 01:36:37
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_897.method_24088(net.minecraft.class_1297, float)" because the return value of "net.minecraft.class_898.method_3953(net.minecraft.class_1297)" is null
	at net.minecraft.class_898.method_23839(class_898.java:76)
	at qouteall.imm_ptl.core.render.context_management.RenderStates.updatePreRenderInfo(RenderStates.java:107)
	at net.minecraft.class_757.handler$fmo000$onFarBeforeRendering(class_757.java:5077)
	at net.minecraft.class_757.method_3192(class_757.java)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:

The version is 1.19.2

**Comment by Talmori** [comment]
For the first issue, I couldn't reproduce it with just Statues Classic and DrippyLoadingScreen. Could you please upload your latest.log.

For the second, there was a conflict with immersive portals on servers. I've uploaded a new version to Modrinth that should hopefully solve the problem.

**Comment by Em4rg** [comment]
[latest.log](https://github.com/Talsumi/MCStatuesClassic/files/9899421/latest.log)

There it is

**Comment by Talmori** [comment]
Sorry, I should have specified. Can you please upload your latest.log after trying to launch the game with both Statues Classic and DrippyLoadingScreen?

**Comment by Em4rg** [comment]
Sure is this 
[latest.log](https://github.com/Talsumi/MCStatuesClassic/files/9911650/latest.log)

**Comment by Talmori** [comment]
I've created a new version with a tweak that _may_ work, and put in some debug log messages.
The file is at https://github.com/Talsumi/MCStatuesClassic/releases/tag/debug, or I could upload it to Modrinth if you prefer.
Please upload your latest.log again after trying to run it.

**Comment by Em4rg** [comment]
Okey I already tried it and the infinite loading screen no longer occurs, it lets me enter a world perfectly, but when I want to create a statue minecraft crashes. 

This is the latest.log when starting minecraft
[latest.log](https://github.com/Talsumi/MCStatuesClassic/files/9926124/latest.log)

**Comment by Talmori** [comment]
Okay, If the issue is what I think it is, this version (debug-2) should work.
https://github.com/Talsumi/MCStatuesClassic/releases/tag/debug

**Comment by Em4rg** [comment]
Nope, still crashes

**Comment by Talmori** [comment]
What's the log?

**Comment by Em4rg** [comment]
[latest.log](https://github.com/Talsumi/MCStatuesClassic/files/9935385/latest.log)

**Comment by Talmori** [comment]
Well it's a different error at least. This time it's a conflict with 3d Skin Layers, that I'm not entirely sure how to solve. I'll have to think on this a bit.

**Comment by Em4rg** [comment]
sure, thank you very much for your attention

**Comment by Talmori** [comment]
I've managed to fix the crash with 3d Skin Layers, although statues will still render like vanilla when it's installed.
All the things I've fixed here have been uploaded to Modrinth. (versions 1.18.2-1.0.4 & 1.19.2-1.0.2)

**Comment by Em4rg** [comment]
Ok, everything works correctly, thank you very much .

**Comment by Talmori** [comment]
Coolio.
